version: '3.8'
name: replica-set
services:
  sh0-mongo1:
    container_name: sh0-mongo1
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh0/:/config/
      - ./mongodb/data/sh0/rs1/:/data/
    networks:
      - mongors-network
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "bash", "/config/entrypoint.sh" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  sh0-mongo2:
    container_name: sh0-mongo2
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh0/:/config/
      - ./mongodb/data/sh0/rs2/:/data/
    networks:
      - mongors-network
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  sh0-mongo3:
    container_name: sh0-mongo3
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh0/:/config/
      - ./mongodb/data/sh0/rs3/:/data/
    networks:
      - mongors-network
    ports:
      - 27023:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  sh1-mongo1:
    container_name: sh1-mongo1
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh1/:/config/
      - ./mongodb/data/sh1/rs1/:/data/
    networks:
      - mongors-network
    ports:
      - 27024:27017
    restart: always
    entrypoint: [ "bash", "/config/entrypoint.sh" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  sh1-mongo2:
    container_name: sh1-mongo2
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh1/:/config/
      - ./mongodb/data/sh1/rs2/:/data/
    networks:
      - mongors-network
    ports:
      - 27025:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  sh1-mongo3:
    container_name: sh1-mongo3
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/replica_set/sh1/:/config/
      - ./mongodb/data/sh1/rs3/:/data/
    networks:
      - mongors-network
    ports:
      - 27026:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  configdb1:
    container_name: configdb1
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/configdb/:/config/
      - ./mongodb/data/configdb/:/data/
    networks:
      - mongors-network
    ports:
      - 27031:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  configdb2:
    container_name: configdb2
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/configdb/:/config/
      - ./mongodb/data/configdb2/:/data/
    networks:
      - mongors-network
    ports:
      - 27032:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

  mongos:
    container_name: mongos
    image: mongo:6.0.5
    volumes:
      - ./mongodb/keys/:/keys/
      - ./mongodb/mongos/:/config/
      - ./mongodb/data/mongos/:/data/
    networks:
      - mongors-network
    ports:
      - 27041:27017
    restart: always
    entrypoint: [ "mongos", "--config", "/config/mongod.cfg" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s

networks:
  mongors-network:
    driver: bridge
